name: adapter_plus
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.14
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.11.9
  - python-dateutil=2.9.0
  - python_abi=3.11
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - array-record==0.5.1
      - astunparse==1.6.3
      - attrs==23.2.0
      - cachetools==5.3.3
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - dm-tree==0.1.8
      - docstring-parser==0.16
      - etils==1.9.2
      - filelock==3.15.4
      - flatbuffers==24.3.25
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gast==0.6.0
      - google-auth==2.32.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - googleapis-common-protos==1.63.2
      - grpcio==1.64.1
      - h5py==3.11.0
      - huggingface-hub==0.23.4
      - hydra-core==1.3.2
      - idna==3.7
      - immutabledict==4.2.0
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - keras==2.15.0
      - libclang==18.1.1
      - lightning==2.3.3
      - lightning-utilities==0.11.3.post0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - namex==0.0.8
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvcc-cu12==12.3.107
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opt-einsum==3.3.0
      - optree==0.12.1
      - pandas==2.2.2
      - pillow==10.4.0
      - promise==2.3
      - protobuf==4.25.3
      - psutil==6.0.0
      - pyarrow==16.1.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pytorch-lightning==2.3.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rsa==4.9
      - safetensors==0.4.3
      - simple-parsing==0.1.5
      - sympy==1.13.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==4.9.6
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.15.0
      - termcolor==2.4.0
      - timm==1.0.7
      - toml==0.10.2
      - torch==2.3.1
      - torchaudio==2.3.1
      - torchmetrics==1.4.0.post0
      - torchvision==0.18.1
      - tqdm==4.66.4
      - triton==2.3.1
      - typeguard==2.13.3
      - tzdata==2024.1
      - urllib3==2.2.2
      - werkzeug==3.0.3
      - wrapt==1.14.1
      - yarl==1.9.4
